### ISSUE TITLE
安装成功后service.log中出现错误

### ISSUE THREAD

**Issue by pianranjinghong** [Magisk-Modules-Repo/v2ray#55]
配置没问题，
运行结果：V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/arm64)
A unified platform for anti-censorship.
2020/04/11 04:34:46 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message>
v2ctl> Read config:  /data/v2ray/config.json
Configuration OK.
[Info]: Starting v2ray service.
[Info]: v2ray service is running. ( PID: 16489 )
运行后service.log中日志
V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/arm64)
A unified platform for anti-censorship.
main: failed to read config files: [/data/v2ray/config.json] > v2ray.com/core/main/json: failed to execute v2ctl to convert config file. > v2ray.com/core/common/platform/ctlcmd: failed to execute v2ctl: 
v2ctl> Read config:  /data/v2ray/config.json
panic: open /data/v2ray/config.json: required key not available

goroutine 1 [running]:
v2ray.com/core/common.Must(...)
	v2ray.com/core/common/common.go:17
v2ray.com/core/infra/control.(*ConfigCommand).Execute(0xa48048, 0x40000a2170, 0x1, 0x1, 0x40000b3cc8, 0x54cf01)
	v2ray.com/core/infra/control/config.go:42 +0x590
main.main()
	v2ray.com/core/infra/control/main/main.go:35 +0x1ec > exit status 2
error.log里的日志如下：
V2Ray 4.23.1 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.13 linux/arm64)
A unified platform for anti-censorship.
2020/04/11 01:31:40 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  /data/v2ray/config.json
2020/04/11 01:31:40 [Info] v2ray.com/core/app/dns: DNS: created udp client inited for 1.1.1.1:53
2020/04/11 01:31:40 [Info] v2ray.com/core/app/dns: DNS: created udp client inited for 114.114.114.114:53
2020/04/11 01:31:40 [Info] v2ray.com/core/app/dns: DNS: created localhost client
2020/04/11 01:31:40 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 0.0.0.0:65534
2020/04/11 01:31:40 [Info] v2ray.com/core/transport/internet/udp: listening UDP on 0.0.0.0:65534
2020/04/11 01:31:40 [Info] v2ray.com/core/transport/internet: failed to apply socket options to incoming connection > v2ray.com/core/transport/internet: failed to set IP_TRANSPARENT > operation not permitted
2020/04/11 01:31:40 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 0.0.0.0:65535
2020/04/11 01:31:40 [Info] v2ray.com/core/transport/internet: failed to apply socket options to incoming connection > v2ray.com/core/transport/internet: failed to set IP_TRANSPARENT > operation not permitted
2020/04/11 01:31:40 [Info] v2ray.com/core/transport/internet/udp: listening UDP on 0.0.0.0:65535
2020/04/11 01:31:40 [Warning] v2ray.com/core: V2Ray 4.23.1 started

**Comment by moesnow** [comment]
+1 我也是这样，之前同样配置用的好好的，升级了下就出问题了

> 2020/04/13 02:25:13 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 0.0.0.0:65534
> 2020/04/13 02:25:13 [Info] v2ray.com/core/transport/internet/udp: listening UDP on 0.0.0.0:65534
> 2020/04/13 02:25:13 [Info] v2ray.com/core/transport/internet: failed to apply socket options to incoming connection > v2ray.com/core/transport/internet: failed to set IP_TRANSPARENT > operation not permitted
> 2020/04/13 02:25:13 [Info] v2ray.com/core/transport/internet/tcp: listening TCP on 0.0.0.0:65535
> 2020/04/13 02:25:13 [Info] v2ray.com/core/transport/internet: failed to apply socket options to incoming connection > v2ray.com/core/transport/internet: failed to set IP_TRANSPARENT > operation not permitted
> 2020/04/13 02:25:13 [Info] v2ray.com/core/transport/internet/udp: listening UDP on 0.0.0.0:65535
> 2020/04/13 02:25:13 [Warning] v2ray.com/core: V2Ray 4.23.1 started

**Comment by kslr** [comment]
``` /usr/bin/setcap "cap_net_bind_service=+ep cap_net_admin=+ep" /usr/bin/v2ray ```
