### ISSUE TITLE
latest version

### ISSUE THREAD

**Issue by EWF54Y6U7I** [Magisk-Modules-Repo/v2ray#80]
Is this normal？

````
SIGILL: illegal instruction
PC=0x4436c0 m=0 sigcode=1
instruction bytes: 0x0 0x6 0x38 0xd5 0xe0 0x7 0x0 0xf9 0xc0 0x3 0x5f 0xd6 0x0 0x0 0x0 0x0

goroutine 1 [running, locked to thread]:
golang.org/x/sys/cpu.getisar0(0x862140)
        golang.org/x/sys@v0.0.0-20201006155630-ac719f4daadf/cpu/cpu_arm64.s:13 fp=0x4000069d50 sp=0x4000069d50 pc=0x4436c0
golang.org/x/sys/cpu.readARM64Registers()
        golang.org/x/sys@v0.0.0-20201006155630-ac719f4daadf/cpu/cpu_arm64.go:65 +0x30 fp=0x4000069d70 sp=0x4000069d50 pc=0x442ee0
golang.org/x/sys/cpu.doinit()
        golang.org/x/sys@v0.0.0-20201006155630-ac719f4daadf/cpu/cpu_linux_arm64.go:38 +0x2c fp=0x4000069d90 sp=0x4000069d70 pc=0x4431bc
golang.org/x/sys/cpu.archInit()
        golang.org/x/sys@v0.0.0-20201006155630-ac719f4daadf/cpu/cpu_arm64.go:55 +0x20 fp=0x4000069da0 sp=0x4000069d90 pc=0x442e90
golang.org/x/sys/cpu.init.0()
        golang.org/x/sys@v0.0.0-20201006155630-ac719f4daadf/cpu/cpu.go:199 +0x20 fp=0x4000069db0 sp=0x4000069da0 pc=0x442430
runtime.doInit(0xf556a0)
        runtime/proc.go:5625 +0x9c fp=0x4000069df0 sp=0x4000069db0 pc=0x50b4c
runtime.doInit(0xf62280)
        runtime/proc.go:5620 +0x58 fp=0x4000069e30 sp=0x4000069df0 pc=0x50b08
runtime.doInit(0xf5aca0)
        runtime/proc.go:5620 +0x58 fp=0x4000069e70 sp=0x4000069e30 pc=0x50b08
runtime.doInit(0xf5dee0)
        runtime/proc.go:5620 +0x58 fp=0x4000069eb0 sp=0x4000069e70 pc=0x50b08
runtime.doInit(0xf5dc40)
        runtime/proc.go:5620 +0x58 fp=0x4000069ef0 sp=0x4000069eb0 pc=0x50b08
runtime.doInit(0xf63aa0)
        runtime/proc.go:5620 +0x58 fp=0x4000069f30 sp=0x4000069ef0 pc=0x50b08
runtime.doInit(0xf5b420)
        runtime/proc.go:5620 +0x58 fp=0x4000069f70 sp=0x4000069f30 pc=0x50b08
runtime.main()
        runtime/proc.go:191 +0x1b8 fp=0x4000069fd0 sp=0x4000069f70 pc=0x439c8
runtime.goexit()
        runtime/asm_arm64.s:1136 +0x4 fp=0x4000069fd0 sp=0x4000069fd0 pc=0x72e34

r0      0x1
r1      0x40000683a0
r2      0x4000069d70
r3      0x40000938f0
r4      0xa81ec0
r5      0x678
r6      0x1000
r7      0x6
r8      0xf9
r9      0x400009391f
r10     0x1000
r11     0x1
r12     0xa61624
r13     0x0
r14     0xf9
r15     0x0
r16     0x0
r17     0x6
r18     0x0
r19     0xf6a858
r20     0x4000069b10
r21     0x4000069c28
r22     0x4000002000
r23     0x0
r24     0x0
r25     0x0
r26     0xf556d8
r27     0xff7cb7
r28     0x4000000180
r29     0x4000069d48
lr      0x442ee0
sp      0x4000069d50
pc      0x4436c0
fault   0x0
````

![Screenshot_20201011-174401232](https://user-images.githubusercontent.com/55339634/95676145-a8f9d780-0bee-11eb-9530-531190708a21.jpg)

**Comment by Rasta0501** [comment]
我也是，918版本，现在卸载了暂时用ng

**Comment by moesnow** [comment]
同

**Comment by whyou** [comment]
试试更新二进制文件。可以直接重新安装模块，会自动更新为最新二进制。

**Comment by EWF54Y6U7I** [comment]
> 试试更新二进制文件。可以直接重新安装模块，会自动更新为最新二进制。

重装模块试过好几次了，还是这样的。。。

**Comment by moesnow** [comment]
刚刚试了手动把 /data/adb/modules/v2ray/system/bin 里面的 v2ray 和 v2ctl 替换成 4.30.0 版本的能正常用了

**Comment by whyou** [comment]
试试手动下载替换（上一版本）二进制文件？

**Comment by 7D0B1564B9764BBE** [comment]
上一版本在哪下载？
![RM3RG4SF3DVDP~P U7JOAUK](https://user-images.githubusercontent.com/55339634/95681905-f12bf080-0c14-11eb-9ed1-fb6948c74346.gif)

**Comment by EWF54Y6U7I** [comment]
> 试试手动下载替换（上一版本）二进制文件？

行了，应该是4.31出了什么BUG了吧(

**Comment by 7D0B1564B9764BBE** [comment]
> 刚刚试了手动把 /data/adb/modules/v2ray/system/bin 里面的 v2ray 和 v2ctl 替换成 4.30.0 版本的能正常用了

**Comment by 7D0B1564B9764BBE** [comment]
啊这，点错了不小心关闭了，把最新版的v2ray-core v4.31二进制文件换成4.30就行了，https://github.com/v2fly/v2ray-core/releases/download/v4.30.0/v2ray-linux-arm64-v8a.zip

**Comment by 7D0B1564B9764BBE** [comment]
> 918版本，现在卸载了暂时用ng

**Comment by dyhkwong** [comment]
1、使用 v4.31.0 arm64 linux 版本，`chmod 0655 /data/adb/modules/v2ray/system/bin/v2ray` 并注释掉 https://github.com/Magisk-Modules-Repo/v2ray/blob/1a55755932c5dc3475d0ac986fb28c26d24aa642/v2ray/scripts/v2ray.service#L85
，查看是否工作

2、使用 v4.31.0 arm64 linux 版本，保持 `v2ray` 的权限为 6755，用 Termux 直接运行 `/data/adb/modules/v2ray/system/bin/v2ray -version`，查看是否报错

3、保持 `v2ray` 的权限为6755，取消上面的注释，将 `v2ray` 用 v4.31.0 arm32 linux 版本替换，查看是否工作

4、保持 `v2ray` 的权限为6755，取消上面的注释，将 `v2ray` 用[在 Termux 中自行编译](https://github.com/v2fly/v2ray-core/issues/298#issuecomment-707540944)或[此处编译好的 Android 版本](https://github.com/v2fly/v2ray-core/issues/298#issuecomment-706865784)替换，查看是否工作

**Comment by opengit** [comment]
重新刷magisk 20.3 版本即可解决，20.4有兼容问题。

**Comment by soundghost** [comment]
感謝樓上各位的分享，我替換4.30.0的二進制文件成功了。
將過程説一下：
手機Nokia 6，magisk 20.4，magisk manager 8.0.3，magisk安裝v2ray之後不要點重啓，pc端adb shell訪問手機，su切換到root用戶。
將v4.30.0的arm64 v8a的二進制文件拷貝到/sdcard/Download/文件夾下，將修改好的config.json文件也拷貝到這裏。
```
cd /sbin/.magisk/mirror/data/adb/modules/v2ray/system/bin/
rm -rf v2ray
cp /sdcard/Download/v2ray .
```
查看一下v2ctl的屬性，用chmod和chown將拷貝過來的v2ray的用戶組和權限改爲跟v2ctl一樣。
移動/sdcard/Download/config.json文件到/data/v2ray/下覆蓋，修改config.josn的權限及屬性跟別的文件一致。
修改appid.list
```
echo 0 > /data/v2ray/appid.list
```
重啓手機，應該就正常了。
