### ISSUE TITLE
显示无法访问config.json

### ISSUE THREAD

**Issue by rainsnow2000** [Magisk-Modules-Repo/v2ray#99]
v2ray service.log显示:
`panic: open /data/v2ray/config.json: permission denied
goroutine 1 [running]:
github.com/v2fly/v2ray-core/v4/common.Must(...)
github.com/v2fly/v2ray-core/v4/common/common.go:27
github.com/v2fly/v2ray-core/v4/main/jsonem.init.0.func1({0x56a5b2d700, 0x400012ff50})
github.com/v2fly/v2ray-core/v4/main/jsonem/jsonem.go:25 +0x438
github.com/v2fly/v2ray-core/v4.LoadConfig({0x56a54baae2, 0x4}, {0x7fe5be05ba, 0x17}, {0x56a5b2d700, 0x400012ff50})
github.com/v2fly/v2ray-core/v4/config.go:68 +0x270
main.startV2Ray()
github.com/v2fly/v2ray-core/v4/main/main.go:109 +
main.main()
github.com/v2fly/v2ray-core/v4/main/main.go:138 +0x9c`

手动在终端中运行service.sh 显示错误

`/system/bin/sh: /data/adb/modules/v2ray/script/v2ray.service: inaccessible or not found`

**Comment by rainsnow2000** [comment]
重装模块解决
